In [94]:
%reload_ext autoreload
%autoreload 2

from main import *
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RepeatedStratifiedKFold, cross_val_score
from scipy.stats import randint
from sklearn.model_selection import GridSearchCV

In [95]:
trials, y = get_trials_and_labels(trial_kwargs={'crop_start_end': [7, 15]})

Getting epochs for filename data/dasps_raw_mat/S01.mat
Not setting metadata
2 matching events found
No baseline correction applied
0 projection items activated
Getting epochs for filename data/dasps_raw_mat/S01.mat
Not setting metadata
2 matching events found
No baseline correction applied
0 projection items activated
Getting epochs for filename data/dasps_raw_mat/S02.mat
Not setting metadata
2 matching events found
No baseline correction applied
0 projection items activated
Getting epochs for filename data/dasps_raw_mat/S02.mat
Not setting metadata
2 matching events found
No baseline correction applied
0 projection items activated
Getting epochs for filename data/dasps_raw_mat/S02.mat
Not setting metadata
2 matching events found
No baseline correction applied
0 projection items activated
Getting epochs for filename data/dasps_raw_mat/S02.mat
Not setting metadata
2 matching events found
No baseline correction applied
0 projection items activated
Getting epochs for filename data/dasps_r

/Users/jakubblaha/Documents/thesis/thesis-python/main.py:47: RuntimeWarning: tmax is not in time interval. tmax is set to <class 'mne.epochs.EpochsArray'>.tmax (14.9922 s)
  self.epoch = epoch.crop(tmin=crop_start_end[0], tmax=crop_start_end[1])
/Users/jakubblaha/Documents/thesis/thesis-python/main.py:47: RuntimeWarning: tmax is not in time interval. tmax is set to <class 'mne.epochs.EpochsArray'>.tmax (14.9922 s)
  self.epoch = epoch.crop(tmin=crop_start_end[0], tmax=crop_start_end[1])
/Users/jakubblaha/Documents/thesis/thesis-python/main.py:47: RuntimeWarning: tmax is not in time interval. tmax is set to <class 'mne.epochs.EpochsArray'>.tmax (14.9922 s)
  self.epoch = epoch.crop(tmin=crop_start_end[0], tmax=crop_start_end[1])
/Users/jakubblaha/Documents/thesis/thesis-python/main.py:47: RuntimeWarning: tmax is not in time interval. tmax is set to <class 'mne.epochs.EpochsArray'>.tmax (14.9922 s)
  self.epoch = epoch.crop(tmin=crop_start_end[0], tmax=crop_start_end[1])
/Users/jakubblah

[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


[Connectivity computation done]
[ 4  8 10 13 30 45]
(6,)
[ 4  8 10 13 30 45]
(6,)
only using indices for lower-triangular matrix
Connectivity computation...
   Processing epoch 1 / 1 ...


/Users/jakubblaha/Documents/thesis/thesis-python/main.py:122: RuntimeWarning: There were no Annotations stored in <EpochsArray | 1 events (all good), 7 – 14.992 s (baseline off), ~127 kB, data loaded,
 '1': 1>, so metadata was not modified.
  res = mne_connectivity.spectral_connectivity_time(


KeyboardInterrupt: 

In [ ]:
len(trials[0].features)

812

In [ ]:
selector = DatasetPreprocessor(trials)
selected = selector.select_k_best()
len(selector.selected_features)

11

In [100]:
reduced_X, y = selector.get_data()

print(reduced_X.shape)

# Define the parameter distribution
param_grid = {
    'n_estimators': [i for i in range(10, 500, 50)],
    'max_depth': [i for i in range(10, 51, 10)],
    'min_samples_split': [i for i in range(2, 10, 2)],
    'min_samples_leaf': [i for i in range(1, 5)],
    'max_features': [None, 'sqrt', 'log2']
}

rf = RandomForestClassifier()
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=2, random_state=0)
# score = cross_val_score(rf, reduced_X, y, scoring='accuracy', cv=cv, n_jobs=-1)
random_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=cv, n_jobs=-1, scoring='accuracy', verbose=1)
random_search.fit(reduced_X, y)

print("Best parameters found: ", random_search.best_params_)
print("Best accuracy found: ", random_search.best_score_)

(312, 11)
Fitting 20 folds for each of 2400 candidates, totalling 48000 fits


/Users/jakubblaha/.local/share/virtualenvs/thesis-python-yCK4mToH/lib/python3.12/site-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


Best parameters found:  {'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 260}
Best accuracy found:  0.8332157258064516


In [101]:
selector.selected_features

array(['time_rms_F7', 'time_hurst_exp_F7', 'rel_pow_theta_O2',
       'rel_pow_alpha-2_O2', 'rel_pow_alpha-2_P8', 'conn_alpha-1_F4_T7',
       'conn_alpha-2_T7_AF3', 'conn_alpha-2_T7_F7', 'conn_alpha-2_T7_F3',
       'conn_alpha-2_F4_T7', 'conn_alpha-2_AF4_T7'], dtype=object)